// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/abi.dart';
import 'api/cpu.dart';
import 'api/lifecycle.dart';
import 'api/memory.dart';
import 'api/os.dart';
import 'api/smoke.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<CpuLoadSampleDto>
  dco_decode_StreamSink_cpu_load_sample_dto_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CGroupLimitsDto dco_decode_box_autoadd_c_group_limits_dto(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  LoadAverageDto dco_decode_box_autoadd_load_average_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CGroupLimitsDto dco_decode_c_group_limits_dto(dynamic raw);

  @protected
  CGroupLimitsReadingDto dco_decode_c_group_limits_reading_dto(dynamic raw);

  @protected
  CpuCoreDto dco_decode_cpu_core_dto(dynamic raw);

  @protected
  CpuInfoDto dco_decode_cpu_info_dto(dynamic raw);

  @protected
  CpuLoadSampleDto dco_decode_cpu_load_sample_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  InitResult dco_decode_init_result(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CpuCoreDto> dco_decode_list_cpu_core_dto(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  LoadAverageDto dco_decode_load_average_dto(dynamic raw);

  @protected
  LoadAverageReadingDto dco_decode_load_average_reading_dto(dynamic raw);

  @protected
  MemoryInfoDto dco_decode_memory_info_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CGroupLimitsDto? dco_decode_opt_box_autoadd_c_group_limits_dto(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  LoadAverageDto? dco_decode_opt_box_autoadd_load_average_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  List<CpuCoreDto>? dco_decode_opt_list_cpu_core_dto(dynamic raw);

  @protected
  OsInfoDto dco_decode_os_info_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<CpuLoadSampleDto>
  sse_decode_StreamSink_cpu_load_sample_dto_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CGroupLimitsDto sse_decode_box_autoadd_c_group_limits_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  LoadAverageDto sse_decode_box_autoadd_load_average_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CGroupLimitsDto sse_decode_c_group_limits_dto(SseDeserializer deserializer);

  @protected
  CGroupLimitsReadingDto sse_decode_c_group_limits_reading_dto(
    SseDeserializer deserializer,
  );

  @protected
  CpuCoreDto sse_decode_cpu_core_dto(SseDeserializer deserializer);

  @protected
  CpuInfoDto sse_decode_cpu_info_dto(SseDeserializer deserializer);

  @protected
  CpuLoadSampleDto sse_decode_cpu_load_sample_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  InitResult sse_decode_init_result(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CpuCoreDto> sse_decode_list_cpu_core_dto(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  LoadAverageDto sse_decode_load_average_dto(SseDeserializer deserializer);

  @protected
  LoadAverageReadingDto sse_decode_load_average_reading_dto(
    SseDeserializer deserializer,
  );

  @protected
  MemoryInfoDto sse_decode_memory_info_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CGroupLimitsDto? sse_decode_opt_box_autoadd_c_group_limits_dto(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  LoadAverageDto? sse_decode_opt_box_autoadd_load_average_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  List<CpuCoreDto>? sse_decode_opt_list_cpu_core_dto(
    SseDeserializer deserializer,
  );

  @protected
  OsInfoDto sse_decode_os_info_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_cpu_load_sample_dto_Sse(
    RustStreamSink<CpuLoadSampleDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_c_group_limits_dto(
    CGroupLimitsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_load_average_dto(
    LoadAverageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_c_group_limits_dto(
    CGroupLimitsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_c_group_limits_reading_dto(
    CGroupLimitsReadingDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cpu_core_dto(CpuCoreDto self, SseSerializer serializer);

  @protected
  void sse_encode_cpu_info_dto(CpuInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_cpu_load_sample_dto(
    CpuLoadSampleDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_init_result(InitResult self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cpu_core_dto(
    List<CpuCoreDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_load_average_dto(
    LoadAverageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_load_average_reading_dto(
    LoadAverageReadingDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_memory_info_dto(MemoryInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_c_group_limits_dto(
    CGroupLimitsDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_load_average_dto(
    LoadAverageDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_cpu_core_dto(
    List<CpuCoreDto>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_os_info_dto(OsInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
