// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/abi.dart';
import 'api/cpu.dart';
import 'api/disks.dart';
import 'api/lifecycle.dart';
import 'api/memory.dart';
import 'api/os.dart';
import 'api/smoke.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 2075512725;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'dart_sysinfo_native',
        ioDirectory: '../native/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<CpuLoadSampleDto> crateApiCpuCpuLoadStream({
    required BigInt intervalMs,
  });

  CpuInfoDto crateApiCpuCpuSnapshot();

  DisksInfoDto crateApiDisksDisksSnapshot();

  void crateApiLifecycleDispose();

  int crateApiSmokeFrbPlatformSmokePing();

  InitResult crateApiLifecycleInit();

  MemoryInfoDto crateApiMemoryMemorySnapshot();

  String crateApiAbiNativeCrateVersion();

  OsInfoDto crateApiOsOsSnapshot();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<CpuLoadSampleDto> crateApiCpuCpuLoadStream({
    required BigInt intervalMs,
  }) {
    final sink = RustStreamSink<CpuLoadSampleDto>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_cpu_load_sample_dto_Sse(sink, serializer);
          sse_encode_u_64(intervalMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuLoadStreamConstMeta,
        argValues: [sink, intervalMs],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCpuCpuLoadStreamConstMeta => const TaskConstMeta(
    debugName: "cpu_load_stream",
    argNames: ["sink", "intervalMs"],
  );

  @override
  CpuInfoDto crateApiCpuCpuSnapshot() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cpu_info_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuSnapshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuSnapshotConstMeta =>
      const TaskConstMeta(debugName: "cpu_snapshot", argNames: []);

  @override
  DisksInfoDto crateApiDisksDisksSnapshot() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_disks_info_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDisksDisksSnapshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDisksDisksSnapshotConstMeta =>
      const TaskConstMeta(debugName: "disks_snapshot", argNames: []);

  @override
  void crateApiLifecycleDispose() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLifecycleDisposeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleDisposeConstMeta =>
      const TaskConstMeta(debugName: "dispose", argNames: []);

  @override
  int crateApiSmokeFrbPlatformSmokePing() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSmokeFrbPlatformSmokePingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmokeFrbPlatformSmokePingConstMeta =>
      const TaskConstMeta(debugName: "frb_platform_smoke_ping", argNames: []);

  @override
  InitResult crateApiLifecycleInit() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_init_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLifecycleInitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleInitConstMeta =>
      const TaskConstMeta(debugName: "init", argNames: []);

  @override
  MemoryInfoDto crateApiMemoryMemorySnapshot() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_memory_info_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMemoryMemorySnapshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryMemorySnapshotConstMeta =>
      const TaskConstMeta(debugName: "memory_snapshot", argNames: []);

  @override
  String crateApiAbiNativeCrateVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAbiNativeCrateVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAbiNativeCrateVersionConstMeta =>
      const TaskConstMeta(debugName: "native_crate_version", argNames: []);

  @override
  OsInfoDto crateApiOsOsSnapshot() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_os_info_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiOsOsSnapshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOsOsSnapshotConstMeta =>
      const TaskConstMeta(debugName: "os_snapshot", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<CpuLoadSampleDto>
  dco_decode_StreamSink_cpu_load_sample_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CGroupLimitsDto dco_decode_box_autoadd_c_group_limits_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_c_group_limits_dto(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  LoadAverageDto dco_decode_box_autoadd_load_average_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_load_average_dto(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CGroupLimitsDto dco_decode_c_group_limits_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CGroupLimitsDto(
      totalMemoryBytes: dco_decode_u_64(arr[0]),
      freeMemoryBytes: dco_decode_u_64(arr[1]),
      freeSwapBytes: dco_decode_u_64(arr[2]),
      rssBytes: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  CGroupLimitsReadingDto dco_decode_c_group_limits_reading_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CGroupLimitsReadingDto(
      supported: dco_decode_bool(arr[0]),
      value: dco_decode_opt_box_autoadd_c_group_limits_dto(arr[1]),
    );
  }

  @protected
  CpuCoreDto dco_decode_cpu_core_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CpuCoreDto(
      name: dco_decode_String(arr[0]),
      vendorId: dco_decode_String(arr[1]),
      brand: dco_decode_String(arr[2]),
      frequencyMhz: dco_decode_u_64(arr[3]),
      usagePercent: dco_decode_f_32(arr[4]),
    );
  }

  @protected
  CpuInfoDto dco_decode_cpu_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CpuInfoDto(
      architecture: dco_decode_String(arr[0]),
      physicalCoreCount: dco_decode_opt_box_autoadd_u_32(arr[1]),
      globalUsagePercent: dco_decode_opt_box_autoadd_f_32(arr[2]),
      cores: dco_decode_opt_list_cpu_core_dto(arr[3]),
    );
  }

  @protected
  CpuLoadSampleDto dco_decode_cpu_load_sample_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CpuLoadSampleDto(
      globalUsagePercent: dco_decode_f_32(arr[0]),
      perCoreUsagePercent: dco_decode_list_prim_f_32_strict(arr[1]),
    );
  }

  @protected
  DiskIoUsageDto dco_decode_disk_io_usage_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DiskIoUsageDto(
      readBytes: dco_decode_u_64(arr[0]),
      writtenBytes: dco_decode_u_64(arr[1]),
      totalReadBytes: dco_decode_u_64(arr[2]),
      totalWrittenBytes: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  DiskKindDto dco_decode_disk_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DiskKindDto.values[raw as int];
  }

  @protected
  DiskVolumeDto dco_decode_disk_volume_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return DiskVolumeDto(
      name: dco_decode_String(arr[0]),
      kind: dco_decode_disk_kind_dto(arr[1]),
      fileSystem: dco_decode_String(arr[2]),
      mountPoint: dco_decode_String(arr[3]),
      totalSpaceBytes: dco_decode_u_64(arr[4]),
      availableSpaceBytes: dco_decode_u_64(arr[5]),
      isRemovable: dco_decode_bool(arr[6]),
      isReadOnly: dco_decode_bool(arr[7]),
      ioUsage: dco_decode_disk_io_usage_dto(arr[8]),
    );
  }

  @protected
  DisksInfoDto dco_decode_disks_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return DisksInfoDto(volumes: dco_decode_list_disk_volume_dto(arr[0]));
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  InitResult dco_decode_init_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return InitResult(
      createdFresh: dco_decode_bool(arr[0]),
      abiVersion: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CpuCoreDto> dco_decode_list_cpu_core_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_cpu_core_dto).toList();
  }

  @protected
  List<DiskVolumeDto> dco_decode_list_disk_volume_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_disk_volume_dto).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  LoadAverageDto dco_decode_load_average_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LoadAverageDto(
      one: dco_decode_f_64(arr[0]),
      five: dco_decode_f_64(arr[1]),
      fifteen: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  LoadAverageReadingDto dco_decode_load_average_reading_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LoadAverageReadingDto(
      supported: dco_decode_bool(arr[0]),
      value: dco_decode_opt_box_autoadd_load_average_dto(arr[1]),
    );
  }

  @protected
  MemoryInfoDto dco_decode_memory_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MemoryInfoDto(
      totalMemoryBytes: dco_decode_u_64(arr[0]),
      freeMemoryBytes: dco_decode_u_64(arr[1]),
      availableMemoryBytes: dco_decode_u_64(arr[2]),
      usedMemoryBytes: dco_decode_u_64(arr[3]),
      totalSwapBytes: dco_decode_u_64(arr[4]),
      freeSwapBytes: dco_decode_u_64(arr[5]),
      usedSwapBytes: dco_decode_u_64(arr[6]),
      cgroupLimits: dco_decode_c_group_limits_reading_dto(arr[7]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  CGroupLimitsDto? dco_decode_opt_box_autoadd_c_group_limits_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_c_group_limits_dto(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  LoadAverageDto? dco_decode_opt_box_autoadd_load_average_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_load_average_dto(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  List<CpuCoreDto>? dco_decode_opt_list_cpu_core_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_cpu_core_dto(raw);
  }

  @protected
  OsInfoDto dco_decode_os_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return OsInfoDto(
      name: dco_decode_opt_String(arr[0]),
      kernelVersion: dco_decode_opt_String(arr[1]),
      osVersion: dco_decode_opt_String(arr[2]),
      longOsVersion: dco_decode_opt_String(arr[3]),
      hostName: dco_decode_opt_String(arr[4]),
      distributionId: dco_decode_String(arr[5]),
      distributionIdLike: dco_decode_list_String(arr[6]),
      kernelLongVersion: dco_decode_String(arr[7]),
      uptimeSeconds: dco_decode_u_64(arr[8]),
      bootTimeSeconds: dco_decode_u_64(arr[9]),
      loadAverage: dco_decode_load_average_reading_dto(arr[10]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<CpuLoadSampleDto>
  sse_decode_StreamSink_cpu_load_sample_dto_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CGroupLimitsDto sse_decode_box_autoadd_c_group_limits_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_c_group_limits_dto(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  LoadAverageDto sse_decode_box_autoadd_load_average_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_load_average_dto(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CGroupLimitsDto sse_decode_c_group_limits_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalMemoryBytes = sse_decode_u_64(deserializer);
    var var_freeMemoryBytes = sse_decode_u_64(deserializer);
    var var_freeSwapBytes = sse_decode_u_64(deserializer);
    var var_rssBytes = sse_decode_u_64(deserializer);
    return CGroupLimitsDto(
      totalMemoryBytes: var_totalMemoryBytes,
      freeMemoryBytes: var_freeMemoryBytes,
      freeSwapBytes: var_freeSwapBytes,
      rssBytes: var_rssBytes,
    );
  }

  @protected
  CGroupLimitsReadingDto sse_decode_c_group_limits_reading_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_supported = sse_decode_bool(deserializer);
    var var_value = sse_decode_opt_box_autoadd_c_group_limits_dto(deserializer);
    return CGroupLimitsReadingDto(supported: var_supported, value: var_value);
  }

  @protected
  CpuCoreDto sse_decode_cpu_core_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_vendorId = sse_decode_String(deserializer);
    var var_brand = sse_decode_String(deserializer);
    var var_frequencyMhz = sse_decode_u_64(deserializer);
    var var_usagePercent = sse_decode_f_32(deserializer);
    return CpuCoreDto(
      name: var_name,
      vendorId: var_vendorId,
      brand: var_brand,
      frequencyMhz: var_frequencyMhz,
      usagePercent: var_usagePercent,
    );
  }

  @protected
  CpuInfoDto sse_decode_cpu_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_architecture = sse_decode_String(deserializer);
    var var_physicalCoreCount = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_globalUsagePercent = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_cores = sse_decode_opt_list_cpu_core_dto(deserializer);
    return CpuInfoDto(
      architecture: var_architecture,
      physicalCoreCount: var_physicalCoreCount,
      globalUsagePercent: var_globalUsagePercent,
      cores: var_cores,
    );
  }

  @protected
  CpuLoadSampleDto sse_decode_cpu_load_sample_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_globalUsagePercent = sse_decode_f_32(deserializer);
    var var_perCoreUsagePercent = sse_decode_list_prim_f_32_strict(
      deserializer,
    );
    return CpuLoadSampleDto(
      globalUsagePercent: var_globalUsagePercent,
      perCoreUsagePercent: var_perCoreUsagePercent,
    );
  }

  @protected
  DiskIoUsageDto sse_decode_disk_io_usage_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_readBytes = sse_decode_u_64(deserializer);
    var var_writtenBytes = sse_decode_u_64(deserializer);
    var var_totalReadBytes = sse_decode_u_64(deserializer);
    var var_totalWrittenBytes = sse_decode_u_64(deserializer);
    return DiskIoUsageDto(
      readBytes: var_readBytes,
      writtenBytes: var_writtenBytes,
      totalReadBytes: var_totalReadBytes,
      totalWrittenBytes: var_totalWrittenBytes,
    );
  }

  @protected
  DiskKindDto sse_decode_disk_kind_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DiskKindDto.values[inner];
  }

  @protected
  DiskVolumeDto sse_decode_disk_volume_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_kind = sse_decode_disk_kind_dto(deserializer);
    var var_fileSystem = sse_decode_String(deserializer);
    var var_mountPoint = sse_decode_String(deserializer);
    var var_totalSpaceBytes = sse_decode_u_64(deserializer);
    var var_availableSpaceBytes = sse_decode_u_64(deserializer);
    var var_isRemovable = sse_decode_bool(deserializer);
    var var_isReadOnly = sse_decode_bool(deserializer);
    var var_ioUsage = sse_decode_disk_io_usage_dto(deserializer);
    return DiskVolumeDto(
      name: var_name,
      kind: var_kind,
      fileSystem: var_fileSystem,
      mountPoint: var_mountPoint,
      totalSpaceBytes: var_totalSpaceBytes,
      availableSpaceBytes: var_availableSpaceBytes,
      isRemovable: var_isRemovable,
      isReadOnly: var_isReadOnly,
      ioUsage: var_ioUsage,
    );
  }

  @protected
  DisksInfoDto sse_decode_disks_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_volumes = sse_decode_list_disk_volume_dto(deserializer);
    return DisksInfoDto(volumes: var_volumes);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  InitResult sse_decode_init_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_createdFresh = sse_decode_bool(deserializer);
    var var_abiVersion = sse_decode_u_32(deserializer);
    return InitResult(
      createdFresh: var_createdFresh,
      abiVersion: var_abiVersion,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CpuCoreDto> sse_decode_list_cpu_core_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CpuCoreDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_cpu_core_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<DiskVolumeDto> sse_decode_list_disk_volume_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DiskVolumeDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_disk_volume_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  LoadAverageDto sse_decode_load_average_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_one = sse_decode_f_64(deserializer);
    var var_five = sse_decode_f_64(deserializer);
    var var_fifteen = sse_decode_f_64(deserializer);
    return LoadAverageDto(one: var_one, five: var_five, fifteen: var_fifteen);
  }

  @protected
  LoadAverageReadingDto sse_decode_load_average_reading_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_supported = sse_decode_bool(deserializer);
    var var_value = sse_decode_opt_box_autoadd_load_average_dto(deserializer);
    return LoadAverageReadingDto(supported: var_supported, value: var_value);
  }

  @protected
  MemoryInfoDto sse_decode_memory_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalMemoryBytes = sse_decode_u_64(deserializer);
    var var_freeMemoryBytes = sse_decode_u_64(deserializer);
    var var_availableMemoryBytes = sse_decode_u_64(deserializer);
    var var_usedMemoryBytes = sse_decode_u_64(deserializer);
    var var_totalSwapBytes = sse_decode_u_64(deserializer);
    var var_freeSwapBytes = sse_decode_u_64(deserializer);
    var var_usedSwapBytes = sse_decode_u_64(deserializer);
    var var_cgroupLimits = sse_decode_c_group_limits_reading_dto(deserializer);
    return MemoryInfoDto(
      totalMemoryBytes: var_totalMemoryBytes,
      freeMemoryBytes: var_freeMemoryBytes,
      availableMemoryBytes: var_availableMemoryBytes,
      usedMemoryBytes: var_usedMemoryBytes,
      totalSwapBytes: var_totalSwapBytes,
      freeSwapBytes: var_freeSwapBytes,
      usedSwapBytes: var_usedSwapBytes,
      cgroupLimits: var_cgroupLimits,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CGroupLimitsDto? sse_decode_opt_box_autoadd_c_group_limits_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_c_group_limits_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  LoadAverageDto? sse_decode_opt_box_autoadd_load_average_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_load_average_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<CpuCoreDto>? sse_decode_opt_list_cpu_core_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_cpu_core_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OsInfoDto sse_decode_os_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_opt_String(deserializer);
    var var_kernelVersion = sse_decode_opt_String(deserializer);
    var var_osVersion = sse_decode_opt_String(deserializer);
    var var_longOsVersion = sse_decode_opt_String(deserializer);
    var var_hostName = sse_decode_opt_String(deserializer);
    var var_distributionId = sse_decode_String(deserializer);
    var var_distributionIdLike = sse_decode_list_String(deserializer);
    var var_kernelLongVersion = sse_decode_String(deserializer);
    var var_uptimeSeconds = sse_decode_u_64(deserializer);
    var var_bootTimeSeconds = sse_decode_u_64(deserializer);
    var var_loadAverage = sse_decode_load_average_reading_dto(deserializer);
    return OsInfoDto(
      name: var_name,
      kernelVersion: var_kernelVersion,
      osVersion: var_osVersion,
      longOsVersion: var_longOsVersion,
      hostName: var_hostName,
      distributionId: var_distributionId,
      distributionIdLike: var_distributionIdLike,
      kernelLongVersion: var_kernelLongVersion,
      uptimeSeconds: var_uptimeSeconds,
      bootTimeSeconds: var_bootTimeSeconds,
      loadAverage: var_loadAverage,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_cpu_load_sample_dto_Sse(
    RustStreamSink<CpuLoadSampleDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_cpu_load_sample_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_c_group_limits_dto(
    CGroupLimitsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_c_group_limits_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_load_average_dto(
    LoadAverageDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_load_average_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_c_group_limits_dto(
    CGroupLimitsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.totalMemoryBytes, serializer);
    sse_encode_u_64(self.freeMemoryBytes, serializer);
    sse_encode_u_64(self.freeSwapBytes, serializer);
    sse_encode_u_64(self.rssBytes, serializer);
  }

  @protected
  void sse_encode_c_group_limits_reading_dto(
    CGroupLimitsReadingDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.supported, serializer);
    sse_encode_opt_box_autoadd_c_group_limits_dto(self.value, serializer);
  }

  @protected
  void sse_encode_cpu_core_dto(CpuCoreDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.vendorId, serializer);
    sse_encode_String(self.brand, serializer);
    sse_encode_u_64(self.frequencyMhz, serializer);
    sse_encode_f_32(self.usagePercent, serializer);
  }

  @protected
  void sse_encode_cpu_info_dto(CpuInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.architecture, serializer);
    sse_encode_opt_box_autoadd_u_32(self.physicalCoreCount, serializer);
    sse_encode_opt_box_autoadd_f_32(self.globalUsagePercent, serializer);
    sse_encode_opt_list_cpu_core_dto(self.cores, serializer);
  }

  @protected
  void sse_encode_cpu_load_sample_dto(
    CpuLoadSampleDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.globalUsagePercent, serializer);
    sse_encode_list_prim_f_32_strict(self.perCoreUsagePercent, serializer);
  }

  @protected
  void sse_encode_disk_io_usage_dto(
    DiskIoUsageDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.readBytes, serializer);
    sse_encode_u_64(self.writtenBytes, serializer);
    sse_encode_u_64(self.totalReadBytes, serializer);
    sse_encode_u_64(self.totalWrittenBytes, serializer);
  }

  @protected
  void sse_encode_disk_kind_dto(DiskKindDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_disk_volume_dto(
    DiskVolumeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_disk_kind_dto(self.kind, serializer);
    sse_encode_String(self.fileSystem, serializer);
    sse_encode_String(self.mountPoint, serializer);
    sse_encode_u_64(self.totalSpaceBytes, serializer);
    sse_encode_u_64(self.availableSpaceBytes, serializer);
    sse_encode_bool(self.isRemovable, serializer);
    sse_encode_bool(self.isReadOnly, serializer);
    sse_encode_disk_io_usage_dto(self.ioUsage, serializer);
  }

  @protected
  void sse_encode_disks_info_dto(DisksInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_disk_volume_dto(self.volumes, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_init_result(InitResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.createdFresh, serializer);
    sse_encode_u_32(self.abiVersion, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_cpu_core_dto(
    List<CpuCoreDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_cpu_core_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_disk_volume_dto(
    List<DiskVolumeDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_disk_volume_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_load_average_dto(
    LoadAverageDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.one, serializer);
    sse_encode_f_64(self.five, serializer);
    sse_encode_f_64(self.fifteen, serializer);
  }

  @protected
  void sse_encode_load_average_reading_dto(
    LoadAverageReadingDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.supported, serializer);
    sse_encode_opt_box_autoadd_load_average_dto(self.value, serializer);
  }

  @protected
  void sse_encode_memory_info_dto(
    MemoryInfoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.totalMemoryBytes, serializer);
    sse_encode_u_64(self.freeMemoryBytes, serializer);
    sse_encode_u_64(self.availableMemoryBytes, serializer);
    sse_encode_u_64(self.usedMemoryBytes, serializer);
    sse_encode_u_64(self.totalSwapBytes, serializer);
    sse_encode_u_64(self.freeSwapBytes, serializer);
    sse_encode_u_64(self.usedSwapBytes, serializer);
    sse_encode_c_group_limits_reading_dto(self.cgroupLimits, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_c_group_limits_dto(
    CGroupLimitsDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_c_group_limits_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_load_average_dto(
    LoadAverageDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_load_average_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_cpu_core_dto(
    List<CpuCoreDto>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_cpu_core_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_os_info_dto(OsInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_String(self.kernelVersion, serializer);
    sse_encode_opt_String(self.osVersion, serializer);
    sse_encode_opt_String(self.longOsVersion, serializer);
    sse_encode_opt_String(self.hostName, serializer);
    sse_encode_String(self.distributionId, serializer);
    sse_encode_list_String(self.distributionIdLike, serializer);
    sse_encode_String(self.kernelLongVersion, serializer);
    sse_encode_u_64(self.uptimeSeconds, serializer);
    sse_encode_u_64(self.bootTimeSeconds, serializer);
    sse_encode_load_average_reading_dto(self.loadAverage, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
