// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1710395181;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__cpu__cpu_load_stream_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "cpu_load_stream",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::cpu::CpuLoadSampleDto,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            let api_interval_ms = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>({
                    crate::api::cpu::cpu_load_stream(api_sink, api_interval_ms);
                })?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__cpu__cpu_snapshot_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "cpu_snapshot",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::cpu::cpu_snapshot())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__disks__disks_snapshot_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "disks_snapshot",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::disks::disks_snapshot())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__lifecycle__dispose_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "dispose",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>({
                    crate::api::lifecycle::dispose();
                })?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__smoke__frb_platform_smoke_ping_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_platform_smoke_ping",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::smoke::frb_platform_smoke_ping())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__lifecycle__init_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::lifecycle::init())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__memory__memory_snapshot_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "memory_snapshot",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::memory::memory_snapshot())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__abi__native_crate_version_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "native_crate_version",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::abi::native_crate_version())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__network__network_snapshot_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "network_snapshot",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::network::network_snapshot())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__network__network_throughput_stream_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "network_throughput_stream",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::network::NetworkThroughputSampleDto,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            let api_interval_ms = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>({
                    crate::api::network::network_throughput_stream(api_sink, api_interval_ms);
                })?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__os__os_snapshot_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "os_snapshot",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::os::os_snapshot())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::cpu::CpuLoadSampleDto, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::network::NetworkThroughputSampleDto,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::memory::CGroupLimitsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_totalMemoryBytes = <u64>::sse_decode(deserializer);
        let mut var_freeMemoryBytes = <u64>::sse_decode(deserializer);
        let mut var_freeSwapBytes = <u64>::sse_decode(deserializer);
        let mut var_rssBytes = <u64>::sse_decode(deserializer);
        return crate::api::memory::CGroupLimitsDto {
            total_memory_bytes: var_totalMemoryBytes,
            free_memory_bytes: var_freeMemoryBytes,
            free_swap_bytes: var_freeSwapBytes,
            rss_bytes: var_rssBytes,
        };
    }
}

impl SseDecode for crate::api::memory::CGroupLimitsReadingDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_supported = <bool>::sse_decode(deserializer);
        let mut var_value = <Option<crate::api::memory::CGroupLimitsDto>>::sse_decode(deserializer);
        return crate::api::memory::CGroupLimitsReadingDto {
            supported: var_supported,
            value: var_value,
        };
    }
}

impl SseDecode for crate::api::cpu::CpuCoreDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_vendorId = <String>::sse_decode(deserializer);
        let mut var_brand = <String>::sse_decode(deserializer);
        let mut var_frequencyMhz = <u64>::sse_decode(deserializer);
        let mut var_usagePercent = <f32>::sse_decode(deserializer);
        return crate::api::cpu::CpuCoreDto {
            name: var_name,
            vendor_id: var_vendorId,
            brand: var_brand,
            frequency_mhz: var_frequencyMhz,
            usage_percent: var_usagePercent,
        };
    }
}

impl SseDecode for crate::api::cpu::CpuInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_architecture = <String>::sse_decode(deserializer);
        let mut var_physicalCoreCount = <Option<u32>>::sse_decode(deserializer);
        let mut var_globalUsagePercent = <Option<f32>>::sse_decode(deserializer);
        let mut var_cores = <Option<Vec<crate::api::cpu::CpuCoreDto>>>::sse_decode(deserializer);
        return crate::api::cpu::CpuInfoDto {
            architecture: var_architecture,
            physical_core_count: var_physicalCoreCount,
            global_usage_percent: var_globalUsagePercent,
            cores: var_cores,
        };
    }
}

impl SseDecode for crate::api::cpu::CpuLoadSampleDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_globalUsagePercent = <f32>::sse_decode(deserializer);
        let mut var_perCoreUsagePercent = <Vec<f32>>::sse_decode(deserializer);
        return crate::api::cpu::CpuLoadSampleDto {
            global_usage_percent: var_globalUsagePercent,
            per_core_usage_percent: var_perCoreUsagePercent,
        };
    }
}

impl SseDecode for crate::api::disks::DiskIoUsageDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_readBytes = <u64>::sse_decode(deserializer);
        let mut var_writtenBytes = <u64>::sse_decode(deserializer);
        let mut var_totalReadBytes = <u64>::sse_decode(deserializer);
        let mut var_totalWrittenBytes = <u64>::sse_decode(deserializer);
        return crate::api::disks::DiskIoUsageDto {
            read_bytes: var_readBytes,
            written_bytes: var_writtenBytes,
            total_read_bytes: var_totalReadBytes,
            total_written_bytes: var_totalWrittenBytes,
        };
    }
}

impl SseDecode for crate::api::disks::DiskKindDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::disks::DiskKindDto::Hdd,
            1 => crate::api::disks::DiskKindDto::Ssd,
            2 => crate::api::disks::DiskKindDto::Unknown,
            _ => unreachable!("Invalid variant for DiskKindDto: {}", inner),
        };
    }
}

impl SseDecode for crate::api::disks::DiskVolumeDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_kind = <crate::api::disks::DiskKindDto>::sse_decode(deserializer);
        let mut var_fileSystem = <String>::sse_decode(deserializer);
        let mut var_mountPoint = <String>::sse_decode(deserializer);
        let mut var_totalSpaceBytes = <u64>::sse_decode(deserializer);
        let mut var_availableSpaceBytes = <u64>::sse_decode(deserializer);
        let mut var_isRemovable = <bool>::sse_decode(deserializer);
        let mut var_isReadOnly = <bool>::sse_decode(deserializer);
        let mut var_ioUsage = <crate::api::disks::DiskIoUsageDto>::sse_decode(deserializer);
        return crate::api::disks::DiskVolumeDto {
            name: var_name,
            kind: var_kind,
            file_system: var_fileSystem,
            mount_point: var_mountPoint,
            total_space_bytes: var_totalSpaceBytes,
            available_space_bytes: var_availableSpaceBytes,
            is_removable: var_isRemovable,
            is_read_only: var_isReadOnly,
            io_usage: var_ioUsage,
        };
    }
}

impl SseDecode for crate::api::disks::DisksInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_volumes = <Vec<crate::api::disks::DiskVolumeDto>>::sse_decode(deserializer);
        return crate::api::disks::DisksInfoDto {
            volumes: var_volumes,
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::lifecycle::InitResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_createdFresh = <bool>::sse_decode(deserializer);
        let mut var_abiVersion = <u32>::sse_decode(deserializer);
        return crate::api::lifecycle::InitResult {
            created_fresh: var_createdFresh,
            abi_version: var_abiVersion,
        };
    }
}

impl SseDecode for crate::api::network::IpNetworkEntryDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_address = <String>::sse_decode(deserializer);
        let mut var_prefixLength = <u8>::sse_decode(deserializer);
        return crate::api::network::IpNetworkEntryDto {
            address: var_address,
            prefix_length: var_prefixLength,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::cpu::CpuCoreDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::cpu::CpuCoreDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::disks::DiskVolumeDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::disks::DiskVolumeDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::network::IpNetworkEntryDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::network::IpNetworkEntryDto>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::network::NetworkInterfaceDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::network::NetworkInterfaceDto>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::network::NetworkThroughputInterfaceDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(
                <crate::api::network::NetworkThroughputInterfaceDto>::sse_decode(deserializer),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<f32>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::os::LoadAverageDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_one = <f64>::sse_decode(deserializer);
        let mut var_five = <f64>::sse_decode(deserializer);
        let mut var_fifteen = <f64>::sse_decode(deserializer);
        return crate::api::os::LoadAverageDto {
            one: var_one,
            five: var_five,
            fifteen: var_fifteen,
        };
    }
}

impl SseDecode for crate::api::os::LoadAverageReadingDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_supported = <bool>::sse_decode(deserializer);
        let mut var_value = <Option<crate::api::os::LoadAverageDto>>::sse_decode(deserializer);
        return crate::api::os::LoadAverageReadingDto {
            supported: var_supported,
            value: var_value,
        };
    }
}

impl SseDecode for crate::api::memory::MemoryInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_totalMemoryBytes = <u64>::sse_decode(deserializer);
        let mut var_freeMemoryBytes = <u64>::sse_decode(deserializer);
        let mut var_availableMemoryBytes = <u64>::sse_decode(deserializer);
        let mut var_usedMemoryBytes = <u64>::sse_decode(deserializer);
        let mut var_totalSwapBytes = <u64>::sse_decode(deserializer);
        let mut var_freeSwapBytes = <u64>::sse_decode(deserializer);
        let mut var_usedSwapBytes = <u64>::sse_decode(deserializer);
        let mut var_cgroupLimits =
            <crate::api::memory::CGroupLimitsReadingDto>::sse_decode(deserializer);
        return crate::api::memory::MemoryInfoDto {
            total_memory_bytes: var_totalMemoryBytes,
            free_memory_bytes: var_freeMemoryBytes,
            available_memory_bytes: var_availableMemoryBytes,
            used_memory_bytes: var_usedMemoryBytes,
            total_swap_bytes: var_totalSwapBytes,
            free_swap_bytes: var_freeSwapBytes,
            used_swap_bytes: var_usedSwapBytes,
            cgroup_limits: var_cgroupLimits,
        };
    }
}

impl SseDecode for crate::api::network::NetworkCumulativeStatsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_totalReceivedBytes = <u64>::sse_decode(deserializer);
        let mut var_totalTransmittedBytes = <u64>::sse_decode(deserializer);
        let mut var_totalPacketsReceived = <u64>::sse_decode(deserializer);
        let mut var_totalPacketsTransmitted = <u64>::sse_decode(deserializer);
        let mut var_totalErrorsOnReceived = <u64>::sse_decode(deserializer);
        let mut var_totalErrorsOnTransmitted = <u64>::sse_decode(deserializer);
        return crate::api::network::NetworkCumulativeStatsDto {
            total_received_bytes: var_totalReceivedBytes,
            total_transmitted_bytes: var_totalTransmittedBytes,
            total_packets_received: var_totalPacketsReceived,
            total_packets_transmitted: var_totalPacketsTransmitted,
            total_errors_on_received: var_totalErrorsOnReceived,
            total_errors_on_transmitted: var_totalErrorsOnTransmitted,
        };
    }
}

impl SseDecode for crate::api::network::NetworkInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_interfaces =
            <Vec<crate::api::network::NetworkInterfaceDto>>::sse_decode(deserializer);
        return crate::api::network::NetworkInfoDto {
            interfaces: var_interfaces,
        };
    }
}

impl SseDecode for crate::api::network::NetworkInterfaceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_macAddress = <String>::sse_decode(deserializer);
        let mut var_ipNetworks =
            <Vec<crate::api::network::IpNetworkEntryDto>>::sse_decode(deserializer);
        let mut var_mtu = <u64>::sse_decode(deserializer);
        let mut var_operationalState =
            <crate::api::network::NetworkOperationalStateDto>::sse_decode(deserializer);
        let mut var_cumulative =
            <crate::api::network::NetworkCumulativeStatsDto>::sse_decode(deserializer);
        return crate::api::network::NetworkInterfaceDto {
            name: var_name,
            mac_address: var_macAddress,
            ip_networks: var_ipNetworks,
            mtu: var_mtu,
            operational_state: var_operationalState,
            cumulative: var_cumulative,
        };
    }
}

impl SseDecode for crate::api::network::NetworkOperationalStateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::network::NetworkOperationalStateDto::Up,
            1 => crate::api::network::NetworkOperationalStateDto::Down,
            2 => crate::api::network::NetworkOperationalStateDto::Testing,
            3 => crate::api::network::NetworkOperationalStateDto::Unknown,
            4 => crate::api::network::NetworkOperationalStateDto::Dormant,
            5 => crate::api::network::NetworkOperationalStateDto::NotPresent,
            6 => crate::api::network::NetworkOperationalStateDto::LowerLayerDown,
            _ => unreachable!("Invalid variant for NetworkOperationalStateDto: {}", inner),
        };
    }
}

impl SseDecode for crate::api::network::NetworkThroughputInterfaceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_receivedBytes = <u64>::sse_decode(deserializer);
        let mut var_transmittedBytes = <u64>::sse_decode(deserializer);
        let mut var_packetsReceived = <u64>::sse_decode(deserializer);
        let mut var_packetsTransmitted = <u64>::sse_decode(deserializer);
        let mut var_errorsOnReceived = <u64>::sse_decode(deserializer);
        let mut var_errorsOnTransmitted = <u64>::sse_decode(deserializer);
        return crate::api::network::NetworkThroughputInterfaceDto {
            name: var_name,
            received_bytes: var_receivedBytes,
            transmitted_bytes: var_transmittedBytes,
            packets_received: var_packetsReceived,
            packets_transmitted: var_packetsTransmitted,
            errors_on_received: var_errorsOnReceived,
            errors_on_transmitted: var_errorsOnTransmitted,
        };
    }
}

impl SseDecode for crate::api::network::NetworkThroughputSampleDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_interfaces =
            <Vec<crate::api::network::NetworkThroughputInterfaceDto>>::sse_decode(deserializer);
        return crate::api::network::NetworkThroughputSampleDto {
            interfaces: var_interfaces,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::memory::CGroupLimitsDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::memory::CGroupLimitsDto>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::os::LoadAverageDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::os::LoadAverageDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<crate::api::cpu::CpuCoreDto>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<crate::api::cpu::CpuCoreDto>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::os::OsInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <Option<String>>::sse_decode(deserializer);
        let mut var_kernelVersion = <Option<String>>::sse_decode(deserializer);
        let mut var_osVersion = <Option<String>>::sse_decode(deserializer);
        let mut var_longOsVersion = <Option<String>>::sse_decode(deserializer);
        let mut var_hostName = <Option<String>>::sse_decode(deserializer);
        let mut var_distributionId = <String>::sse_decode(deserializer);
        let mut var_distributionIdLike = <Vec<String>>::sse_decode(deserializer);
        let mut var_kernelLongVersion = <String>::sse_decode(deserializer);
        let mut var_uptimeSeconds = <u64>::sse_decode(deserializer);
        let mut var_bootTimeSeconds = <u64>::sse_decode(deserializer);
        let mut var_loadAverage = <crate::api::os::LoadAverageReadingDto>::sse_decode(deserializer);
        return crate::api::os::OsInfoDto {
            name: var_name,
            kernel_version: var_kernelVersion,
            os_version: var_osVersion,
            long_os_version: var_longOsVersion,
            host_name: var_hostName,
            distribution_id: var_distributionId,
            distribution_id_like: var_distributionIdLike,
            kernel_long_version: var_kernelLongVersion,
            uptime_seconds: var_uptimeSeconds,
            boot_time_seconds: var_bootTimeSeconds,
            load_average: var_loadAverage,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__cpu__cpu_load_stream_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__cpu__cpu_snapshot_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__disks__disks_snapshot_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__lifecycle__dispose_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__smoke__frb_platform_smoke_ping_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__lifecycle__init_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__memory__memory_snapshot_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__abi__native_crate_version_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__network__network_snapshot_impl(ptr, rust_vec_len, data_len),
        10 => {
            wire__crate__api__network__network_throughput_stream_impl(ptr, rust_vec_len, data_len)
        }
        11 => wire__crate__api__os__os_snapshot_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::CGroupLimitsDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.total_memory_bytes.into_into_dart().into_dart(),
            self.free_memory_bytes.into_into_dart().into_dart(),
            self.free_swap_bytes.into_into_dart().into_dart(),
            self.rss_bytes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::CGroupLimitsDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::CGroupLimitsDto>
    for crate::api::memory::CGroupLimitsDto
{
    fn into_into_dart(self) -> crate::api::memory::CGroupLimitsDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::CGroupLimitsReadingDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.supported.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::CGroupLimitsReadingDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::CGroupLimitsReadingDto>
    for crate::api::memory::CGroupLimitsReadingDto
{
    fn into_into_dart(self) -> crate::api::memory::CGroupLimitsReadingDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::cpu::CpuCoreDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.vendor_id.into_into_dart().into_dart(),
            self.brand.into_into_dart().into_dart(),
            self.frequency_mhz.into_into_dart().into_dart(),
            self.usage_percent.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::cpu::CpuCoreDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::cpu::CpuCoreDto>
    for crate::api::cpu::CpuCoreDto
{
    fn into_into_dart(self) -> crate::api::cpu::CpuCoreDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::cpu::CpuInfoDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.architecture.into_into_dart().into_dart(),
            self.physical_core_count.into_into_dart().into_dart(),
            self.global_usage_percent.into_into_dart().into_dart(),
            self.cores.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::cpu::CpuInfoDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::cpu::CpuInfoDto>
    for crate::api::cpu::CpuInfoDto
{
    fn into_into_dart(self) -> crate::api::cpu::CpuInfoDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::cpu::CpuLoadSampleDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.global_usage_percent.into_into_dart().into_dart(),
            self.per_core_usage_percent.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::cpu::CpuLoadSampleDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::cpu::CpuLoadSampleDto>
    for crate::api::cpu::CpuLoadSampleDto
{
    fn into_into_dart(self) -> crate::api::cpu::CpuLoadSampleDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::disks::DiskIoUsageDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.read_bytes.into_into_dart().into_dart(),
            self.written_bytes.into_into_dart().into_dart(),
            self.total_read_bytes.into_into_dart().into_dart(),
            self.total_written_bytes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::disks::DiskIoUsageDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::disks::DiskIoUsageDto>
    for crate::api::disks::DiskIoUsageDto
{
    fn into_into_dart(self) -> crate::api::disks::DiskIoUsageDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::disks::DiskKindDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Hdd => 0.into_dart(),
            Self::Ssd => 1.into_dart(),
            Self::Unknown => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::disks::DiskKindDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::disks::DiskKindDto>
    for crate::api::disks::DiskKindDto
{
    fn into_into_dart(self) -> crate::api::disks::DiskKindDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::disks::DiskVolumeDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.file_system.into_into_dart().into_dart(),
            self.mount_point.into_into_dart().into_dart(),
            self.total_space_bytes.into_into_dart().into_dart(),
            self.available_space_bytes.into_into_dart().into_dart(),
            self.is_removable.into_into_dart().into_dart(),
            self.is_read_only.into_into_dart().into_dart(),
            self.io_usage.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::disks::DiskVolumeDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::disks::DiskVolumeDto>
    for crate::api::disks::DiskVolumeDto
{
    fn into_into_dart(self) -> crate::api::disks::DiskVolumeDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::disks::DisksInfoDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.volumes.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::disks::DisksInfoDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::disks::DisksInfoDto>
    for crate::api::disks::DisksInfoDto
{
    fn into_into_dart(self) -> crate::api::disks::DisksInfoDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::lifecycle::InitResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.created_fresh.into_into_dart().into_dart(),
            self.abi_version.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::lifecycle::InitResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::lifecycle::InitResult>
    for crate::api::lifecycle::InitResult
{
    fn into_into_dart(self) -> crate::api::lifecycle::InitResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::IpNetworkEntryDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.address.into_into_dart().into_dart(),
            self.prefix_length.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::IpNetworkEntryDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::IpNetworkEntryDto>
    for crate::api::network::IpNetworkEntryDto
{
    fn into_into_dart(self) -> crate::api::network::IpNetworkEntryDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::os::LoadAverageDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.one.into_into_dart().into_dart(),
            self.five.into_into_dart().into_dart(),
            self.fifteen.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::os::LoadAverageDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::os::LoadAverageDto>
    for crate::api::os::LoadAverageDto
{
    fn into_into_dart(self) -> crate::api::os::LoadAverageDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::os::LoadAverageReadingDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.supported.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::os::LoadAverageReadingDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::os::LoadAverageReadingDto>
    for crate::api::os::LoadAverageReadingDto
{
    fn into_into_dart(self) -> crate::api::os::LoadAverageReadingDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::MemoryInfoDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.total_memory_bytes.into_into_dart().into_dart(),
            self.free_memory_bytes.into_into_dart().into_dart(),
            self.available_memory_bytes.into_into_dart().into_dart(),
            self.used_memory_bytes.into_into_dart().into_dart(),
            self.total_swap_bytes.into_into_dart().into_dart(),
            self.free_swap_bytes.into_into_dart().into_dart(),
            self.used_swap_bytes.into_into_dart().into_dart(),
            self.cgroup_limits.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::MemoryInfoDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::MemoryInfoDto>
    for crate::api::memory::MemoryInfoDto
{
    fn into_into_dart(self) -> crate::api::memory::MemoryInfoDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::NetworkCumulativeStatsDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.total_received_bytes.into_into_dart().into_dart(),
            self.total_transmitted_bytes.into_into_dart().into_dart(),
            self.total_packets_received.into_into_dart().into_dart(),
            self.total_packets_transmitted.into_into_dart().into_dart(),
            self.total_errors_on_received.into_into_dart().into_dart(),
            self.total_errors_on_transmitted
                .into_into_dart()
                .into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::NetworkCumulativeStatsDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::NetworkCumulativeStatsDto>
    for crate::api::network::NetworkCumulativeStatsDto
{
    fn into_into_dart(self) -> crate::api::network::NetworkCumulativeStatsDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::NetworkInfoDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.interfaces.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::NetworkInfoDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::NetworkInfoDto>
    for crate::api::network::NetworkInfoDto
{
    fn into_into_dart(self) -> crate::api::network::NetworkInfoDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::NetworkInterfaceDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.mac_address.into_into_dart().into_dart(),
            self.ip_networks.into_into_dart().into_dart(),
            self.mtu.into_into_dart().into_dart(),
            self.operational_state.into_into_dart().into_dart(),
            self.cumulative.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::NetworkInterfaceDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::NetworkInterfaceDto>
    for crate::api::network::NetworkInterfaceDto
{
    fn into_into_dart(self) -> crate::api::network::NetworkInterfaceDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::NetworkOperationalStateDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Up => 0.into_dart(),
            Self::Down => 1.into_dart(),
            Self::Testing => 2.into_dart(),
            Self::Unknown => 3.into_dart(),
            Self::Dormant => 4.into_dart(),
            Self::NotPresent => 5.into_dart(),
            Self::LowerLayerDown => 6.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::NetworkOperationalStateDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::NetworkOperationalStateDto>
    for crate::api::network::NetworkOperationalStateDto
{
    fn into_into_dart(self) -> crate::api::network::NetworkOperationalStateDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::NetworkThroughputInterfaceDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.received_bytes.into_into_dart().into_dart(),
            self.transmitted_bytes.into_into_dart().into_dart(),
            self.packets_received.into_into_dart().into_dart(),
            self.packets_transmitted.into_into_dart().into_dart(),
            self.errors_on_received.into_into_dart().into_dart(),
            self.errors_on_transmitted.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::NetworkThroughputInterfaceDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::NetworkThroughputInterfaceDto>
    for crate::api::network::NetworkThroughputInterfaceDto
{
    fn into_into_dart(self) -> crate::api::network::NetworkThroughputInterfaceDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::NetworkThroughputSampleDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.interfaces.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::NetworkThroughputSampleDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::NetworkThroughputSampleDto>
    for crate::api::network::NetworkThroughputSampleDto
{
    fn into_into_dart(self) -> crate::api::network::NetworkThroughputSampleDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::os::OsInfoDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.kernel_version.into_into_dart().into_dart(),
            self.os_version.into_into_dart().into_dart(),
            self.long_os_version.into_into_dart().into_dart(),
            self.host_name.into_into_dart().into_dart(),
            self.distribution_id.into_into_dart().into_dart(),
            self.distribution_id_like.into_into_dart().into_dart(),
            self.kernel_long_version.into_into_dart().into_dart(),
            self.uptime_seconds.into_into_dart().into_dart(),
            self.boot_time_seconds.into_into_dart().into_dart(),
            self.load_average.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::os::OsInfoDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::os::OsInfoDto> for crate::api::os::OsInfoDto {
    fn into_into_dart(self) -> crate::api::os::OsInfoDto {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::cpu::CpuLoadSampleDto, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::network::NetworkThroughputSampleDto,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::memory::CGroupLimitsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.total_memory_bytes, serializer);
        <u64>::sse_encode(self.free_memory_bytes, serializer);
        <u64>::sse_encode(self.free_swap_bytes, serializer);
        <u64>::sse_encode(self.rss_bytes, serializer);
    }
}

impl SseEncode for crate::api::memory::CGroupLimitsReadingDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.supported, serializer);
        <Option<crate::api::memory::CGroupLimitsDto>>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for crate::api::cpu::CpuCoreDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.vendor_id, serializer);
        <String>::sse_encode(self.brand, serializer);
        <u64>::sse_encode(self.frequency_mhz, serializer);
        <f32>::sse_encode(self.usage_percent, serializer);
    }
}

impl SseEncode for crate::api::cpu::CpuInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.architecture, serializer);
        <Option<u32>>::sse_encode(self.physical_core_count, serializer);
        <Option<f32>>::sse_encode(self.global_usage_percent, serializer);
        <Option<Vec<crate::api::cpu::CpuCoreDto>>>::sse_encode(self.cores, serializer);
    }
}

impl SseEncode for crate::api::cpu::CpuLoadSampleDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.global_usage_percent, serializer);
        <Vec<f32>>::sse_encode(self.per_core_usage_percent, serializer);
    }
}

impl SseEncode for crate::api::disks::DiskIoUsageDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.read_bytes, serializer);
        <u64>::sse_encode(self.written_bytes, serializer);
        <u64>::sse_encode(self.total_read_bytes, serializer);
        <u64>::sse_encode(self.total_written_bytes, serializer);
    }
}

impl SseEncode for crate::api::disks::DiskKindDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::disks::DiskKindDto::Hdd => 0,
                crate::api::disks::DiskKindDto::Ssd => 1,
                crate::api::disks::DiskKindDto::Unknown => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::disks::DiskVolumeDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <crate::api::disks::DiskKindDto>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.file_system, serializer);
        <String>::sse_encode(self.mount_point, serializer);
        <u64>::sse_encode(self.total_space_bytes, serializer);
        <u64>::sse_encode(self.available_space_bytes, serializer);
        <bool>::sse_encode(self.is_removable, serializer);
        <bool>::sse_encode(self.is_read_only, serializer);
        <crate::api::disks::DiskIoUsageDto>::sse_encode(self.io_usage, serializer);
    }
}

impl SseEncode for crate::api::disks::DisksInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::disks::DiskVolumeDto>>::sse_encode(self.volumes, serializer);
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::lifecycle::InitResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.created_fresh, serializer);
        <u32>::sse_encode(self.abi_version, serializer);
    }
}

impl SseEncode for crate::api::network::IpNetworkEntryDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.address, serializer);
        <u8>::sse_encode(self.prefix_length, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::cpu::CpuCoreDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::cpu::CpuCoreDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::disks::DiskVolumeDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::disks::DiskVolumeDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::network::IpNetworkEntryDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::network::IpNetworkEntryDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::network::NetworkInterfaceDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::network::NetworkInterfaceDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::network::NetworkThroughputInterfaceDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::network::NetworkThroughputInterfaceDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <f32>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::os::LoadAverageDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.one, serializer);
        <f64>::sse_encode(self.five, serializer);
        <f64>::sse_encode(self.fifteen, serializer);
    }
}

impl SseEncode for crate::api::os::LoadAverageReadingDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.supported, serializer);
        <Option<crate::api::os::LoadAverageDto>>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for crate::api::memory::MemoryInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.total_memory_bytes, serializer);
        <u64>::sse_encode(self.free_memory_bytes, serializer);
        <u64>::sse_encode(self.available_memory_bytes, serializer);
        <u64>::sse_encode(self.used_memory_bytes, serializer);
        <u64>::sse_encode(self.total_swap_bytes, serializer);
        <u64>::sse_encode(self.free_swap_bytes, serializer);
        <u64>::sse_encode(self.used_swap_bytes, serializer);
        <crate::api::memory::CGroupLimitsReadingDto>::sse_encode(self.cgroup_limits, serializer);
    }
}

impl SseEncode for crate::api::network::NetworkCumulativeStatsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.total_received_bytes, serializer);
        <u64>::sse_encode(self.total_transmitted_bytes, serializer);
        <u64>::sse_encode(self.total_packets_received, serializer);
        <u64>::sse_encode(self.total_packets_transmitted, serializer);
        <u64>::sse_encode(self.total_errors_on_received, serializer);
        <u64>::sse_encode(self.total_errors_on_transmitted, serializer);
    }
}

impl SseEncode for crate::api::network::NetworkInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::network::NetworkInterfaceDto>>::sse_encode(self.interfaces, serializer);
    }
}

impl SseEncode for crate::api::network::NetworkInterfaceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.mac_address, serializer);
        <Vec<crate::api::network::IpNetworkEntryDto>>::sse_encode(self.ip_networks, serializer);
        <u64>::sse_encode(self.mtu, serializer);
        <crate::api::network::NetworkOperationalStateDto>::sse_encode(
            self.operational_state,
            serializer,
        );
        <crate::api::network::NetworkCumulativeStatsDto>::sse_encode(self.cumulative, serializer);
    }
}

impl SseEncode for crate::api::network::NetworkOperationalStateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::network::NetworkOperationalStateDto::Up => 0,
                crate::api::network::NetworkOperationalStateDto::Down => 1,
                crate::api::network::NetworkOperationalStateDto::Testing => 2,
                crate::api::network::NetworkOperationalStateDto::Unknown => 3,
                crate::api::network::NetworkOperationalStateDto::Dormant => 4,
                crate::api::network::NetworkOperationalStateDto::NotPresent => 5,
                crate::api::network::NetworkOperationalStateDto::LowerLayerDown => 6,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::network::NetworkThroughputInterfaceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <u64>::sse_encode(self.received_bytes, serializer);
        <u64>::sse_encode(self.transmitted_bytes, serializer);
        <u64>::sse_encode(self.packets_received, serializer);
        <u64>::sse_encode(self.packets_transmitted, serializer);
        <u64>::sse_encode(self.errors_on_received, serializer);
        <u64>::sse_encode(self.errors_on_transmitted, serializer);
    }
}

impl SseEncode for crate::api::network::NetworkThroughputSampleDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::network::NetworkThroughputInterfaceDto>>::sse_encode(
            self.interfaces,
            serializer,
        );
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::memory::CGroupLimitsDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::memory::CGroupLimitsDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::os::LoadAverageDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::os::LoadAverageDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<crate::api::cpu::CpuCoreDto>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<crate::api::cpu::CpuCoreDto>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::os::OsInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.name, serializer);
        <Option<String>>::sse_encode(self.kernel_version, serializer);
        <Option<String>>::sse_encode(self.os_version, serializer);
        <Option<String>>::sse_encode(self.long_os_version, serializer);
        <Option<String>>::sse_encode(self.host_name, serializer);
        <String>::sse_encode(self.distribution_id, serializer);
        <Vec<String>>::sse_encode(self.distribution_id_like, serializer);
        <String>::sse_encode(self.kernel_long_version, serializer);
        <u64>::sse_encode(self.uptime_seconds, serializer);
        <u64>::sse_encode(self.boot_time_seconds, serializer);
        <crate::api::os::LoadAverageReadingDto>::sse_encode(self.load_average, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
