// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:dart_sysinfo/src/bridge/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Returns the native crate semver embedded at compile time (PRD §7.3).
String nativeCrateVersion() =>
    RustLib.instance.api.crateApiAbiNativeCrateVersion();
