// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:dart_sysinfo/src/bridge/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_cpu_load_sample`, `cpu_enumeration_supported`, `cpu_load_worker`, `map_cores`, `next_cpu_load_sample`

/// Returns a TTL-backed CPU snapshot (refresh under write lock, TDD §2.2).
CpuInfoDto cpuSnapshot() => RustLib.instance.api.crateApiCpuCpuSnapshot();

/// Spawns a worker that pushes CPU load samples until the Dart listener cancels.
Stream<CpuLoadSampleDto> cpuLoadStream({required BigInt intervalMs}) =>
    RustLib.instance.api.crateApiCpuCpuLoadStream(intervalMs: intervalMs);

/// Per-core CPU fields exposed to Dart via FRB.
class CpuCoreDto {
  const CpuCoreDto({
    required this.name,
    required this.vendorId,
    required this.brand,
    required this.frequencyMhz,
    required this.usagePercent,
  });
  final String name;
  final String vendorId;
  final String brand;
  final BigInt frequencyMhz;
  final double usagePercent;

  @override
  int get hashCode =>
      name.hashCode ^
      vendorId.hashCode ^
      brand.hashCode ^
      frequencyMhz.hashCode ^
      usagePercent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CpuCoreDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          vendorId == other.vendorId &&
          brand == other.brand &&
          frequencyMhz == other.frequencyMhz &&
          usagePercent == other.usagePercent;
}

/// CPU snapshot DTO. `Option` fields carry §4.1 semantics for M1-07 `Reading<T>`.
class CpuInfoDto {
  const CpuInfoDto({
    required this.architecture,
    this.physicalCoreCount,
    this.globalUsagePercent,
    this.cores,
  });
  final String architecture;
  final int? physicalCoreCount;
  final double? globalUsagePercent;
  final List<CpuCoreDto>? cores;

  @override
  int get hashCode =>
      architecture.hashCode ^
      physicalCoreCount.hashCode ^
      globalUsagePercent.hashCode ^
      cores.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CpuInfoDto &&
          runtimeType == other.runtimeType &&
          architecture == other.architecture &&
          physicalCoreCount == other.physicalCoreCount &&
          globalUsagePercent == other.globalUsagePercent &&
          cores == other.cores;
}

/// One CPU load stream tick (plain fields — no `Reading<T>` on streams, TDD §4.1).
class CpuLoadSampleDto {
  const CpuLoadSampleDto({
    required this.globalUsagePercent,
    required this.perCoreUsagePercent,
  });
  final double globalUsagePercent;
  final Float32List perCoreUsagePercent;

  @override
  int get hashCode =>
      globalUsagePercent.hashCode ^ perCoreUsagePercent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CpuLoadSampleDto &&
          runtimeType == other.runtimeType &&
          globalUsagePercent == other.globalUsagePercent &&
          perCoreUsagePercent == other.perCoreUsagePercent;
}
