// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:dart_sysinfo/src/bridge/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_disk_kind`, `map_disk_volume`

/// Returns a TTL-backed disks snapshot (refresh under write lock, TDD §4.4).
DisksInfoDto disksSnapshot() =>
    RustLib.instance.api.crateApiDisksDisksSnapshot();

/// Cumulative disk I/O counters from the last native refresh.
class DiskIoUsageDto {
  const DiskIoUsageDto({
    required this.readBytes,
    required this.writtenBytes,
    required this.totalReadBytes,
    required this.totalWrittenBytes,
  });
  final BigInt readBytes;
  final BigInt writtenBytes;
  final BigInt totalReadBytes;
  final BigInt totalWrittenBytes;

  @override
  int get hashCode =>
      readBytes.hashCode ^
      writtenBytes.hashCode ^
      totalReadBytes.hashCode ^
      totalWrittenBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiskIoUsageDto &&
          runtimeType == other.runtimeType &&
          readBytes == other.readBytes &&
          writtenBytes == other.writtenBytes &&
          totalReadBytes == other.totalReadBytes &&
          totalWrittenBytes == other.totalWrittenBytes;
}

/// Physical disk kind exposed to Dart.
enum DiskKindDto { hdd, ssd, unknown }

/// Single mounted volume in a disks snapshot.
class DiskVolumeDto {
  const DiskVolumeDto({
    required this.name,
    required this.kind,
    required this.fileSystem,
    required this.mountPoint,
    required this.totalSpaceBytes,
    required this.availableSpaceBytes,
    required this.isRemovable,
    required this.isReadOnly,
    required this.ioUsage,
  });
  final String name;
  final DiskKindDto kind;
  final String fileSystem;
  final String mountPoint;
  final BigInt totalSpaceBytes;
  final BigInt availableSpaceBytes;
  final bool isRemovable;
  final bool isReadOnly;
  final DiskIoUsageDto ioUsage;

  @override
  int get hashCode =>
      name.hashCode ^
      kind.hashCode ^
      fileSystem.hashCode ^
      mountPoint.hashCode ^
      totalSpaceBytes.hashCode ^
      availableSpaceBytes.hashCode ^
      isRemovable.hashCode ^
      isReadOnly.hashCode ^
      ioUsage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiskVolumeDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          kind == other.kind &&
          fileSystem == other.fileSystem &&
          mountPoint == other.mountPoint &&
          totalSpaceBytes == other.totalSpaceBytes &&
          availableSpaceBytes == other.availableSpaceBytes &&
          isRemovable == other.isRemovable &&
          isReadOnly == other.isReadOnly &&
          ioUsage == other.ioUsage;
}

/// Disks snapshot DTO returned to Dart via FRB.
class DisksInfoDto {
  const DisksInfoDto({required this.volumes});
  final List<DiskVolumeDto> volumes;

  @override
  int get hashCode => volumes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisksInfoDto &&
          runtimeType == other.runtimeType &&
          volumes == other.volumes;
}
