// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:dart_sysinfo/src/bridge/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initializes shared native state idempotently.
InitResult init() => RustLib.instance.api.crateApiLifecycleInit();

/// Disposes shared native state so a later init can recreate it cleanly.
void dispose() => RustLib.instance.api.crateApiLifecycleDispose();

/// FRB-facing init result returned to Dart after the first native round-trip.
class InitResult {
  const InitResult({required this.createdFresh, required this.abiVersion});

  /// Whether this init created fresh native state.
  final bool createdFresh;

  /// ABI version of the loaded native library.
  final int abiVersion;

  @override
  int get hashCode => createdFresh.hashCode ^ abiVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InitResult &&
          runtimeType == other.runtimeType &&
          createdFresh == other.createdFresh &&
          abiVersion == other.abiVersion;
}
