// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:dart_sysinfo/src/bridge/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_cgroup_limits`

/// Returns a TTL-backed memory snapshot (refresh under write lock, TDD §2.2).
MemoryInfoDto memorySnapshot() =>
    RustLib.instance.api.crateApiMemoryMemorySnapshot();

/// Root cgroup memory limits exposed to Dart via FRB.
class CGroupLimitsDto {
  const CGroupLimitsDto({
    required this.totalMemoryBytes,
    required this.freeMemoryBytes,
    required this.freeSwapBytes,
    required this.rssBytes,
  });
  final BigInt totalMemoryBytes;
  final BigInt freeMemoryBytes;
  final BigInt freeSwapBytes;
  final BigInt rssBytes;

  @override
  int get hashCode =>
      totalMemoryBytes.hashCode ^
      freeMemoryBytes.hashCode ^
      freeSwapBytes.hashCode ^
      rssBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CGroupLimitsDto &&
          runtimeType == other.runtimeType &&
          totalMemoryBytes == other.totalMemoryBytes &&
          freeMemoryBytes == other.freeMemoryBytes &&
          freeSwapBytes == other.freeSwapBytes &&
          rssBytes == other.rssBytes;
}

/// Carries §4.2 tri-state cgroup semantics for M1-08 Dart Reading mapping.
class CGroupLimitsReadingDto {
  const CGroupLimitsReadingDto({required this.supported, this.value});

  /// False on non-Linux → Dart `ReadingUnsupported`.
  final bool supported;

  /// None on Linux when sysinfo returns no cgroup → Dart `ReadingUnavailable`.
  final CGroupLimitsDto? value;

  @override
  int get hashCode => supported.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CGroupLimitsReadingDto &&
          runtimeType == other.runtimeType &&
          supported == other.supported &&
          value == other.value;
}

/// Memory snapshot DTO returned to Dart via FRB.
class MemoryInfoDto {
  const MemoryInfoDto({
    required this.totalMemoryBytes,
    required this.freeMemoryBytes,
    required this.availableMemoryBytes,
    required this.usedMemoryBytes,
    required this.totalSwapBytes,
    required this.freeSwapBytes,
    required this.usedSwapBytes,
    required this.cgroupLimits,
  });
  final BigInt totalMemoryBytes;
  final BigInt freeMemoryBytes;
  final BigInt availableMemoryBytes;
  final BigInt usedMemoryBytes;
  final BigInt totalSwapBytes;
  final BigInt freeSwapBytes;
  final BigInt usedSwapBytes;
  final CGroupLimitsReadingDto cgroupLimits;

  @override
  int get hashCode =>
      totalMemoryBytes.hashCode ^
      freeMemoryBytes.hashCode ^
      availableMemoryBytes.hashCode ^
      usedMemoryBytes.hashCode ^
      totalSwapBytes.hashCode ^
      freeSwapBytes.hashCode ^
      usedSwapBytes.hashCode ^
      cgroupLimits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryInfoDto &&
          runtimeType == other.runtimeType &&
          totalMemoryBytes == other.totalMemoryBytes &&
          freeMemoryBytes == other.freeMemoryBytes &&
          availableMemoryBytes == other.availableMemoryBytes &&
          usedMemoryBytes == other.usedMemoryBytes &&
          totalSwapBytes == other.totalSwapBytes &&
          freeSwapBytes == other.freeSwapBytes &&
          usedSwapBytes == other.usedSwapBytes &&
          cgroupLimits == other.cgroupLimits;
}
