// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:dart_sysinfo/src/bridge/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_network_throughput_sample`, `map_network_interface`, `map_operational_state`, `network_throughput_worker`, `next_network_throughput_sample`

/// Returns a TTL-backed network snapshot (refresh under write lock, TDD §4.5).
NetworkInfoDto networkSnapshot() =>
    RustLib.instance.api.crateApiNetworkNetworkSnapshot();

/// Spawns a worker that pushes network throughput samples until cancelled.
Stream<NetworkThroughputSampleDto> networkThroughputStream({
  required BigInt intervalMs,
}) => RustLib.instance.api.crateApiNetworkNetworkThroughputStream(
  intervalMs: intervalMs,
);

/// IP network assigned to an interface.
class IpNetworkEntryDto {
  const IpNetworkEntryDto({required this.address, required this.prefixLength});
  final String address;
  final int prefixLength;

  @override
  int get hashCode => address.hashCode ^ prefixLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IpNetworkEntryDto &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          prefixLength == other.prefixLength;
}

/// Lifetime cumulative counters for a network interface.
class NetworkCumulativeStatsDto {
  const NetworkCumulativeStatsDto({
    required this.totalReceivedBytes,
    required this.totalTransmittedBytes,
    required this.totalPacketsReceived,
    required this.totalPacketsTransmitted,
    required this.totalErrorsOnReceived,
    required this.totalErrorsOnTransmitted,
  });
  final BigInt totalReceivedBytes;
  final BigInt totalTransmittedBytes;
  final BigInt totalPacketsReceived;
  final BigInt totalPacketsTransmitted;
  final BigInt totalErrorsOnReceived;
  final BigInt totalErrorsOnTransmitted;

  @override
  int get hashCode =>
      totalReceivedBytes.hashCode ^
      totalTransmittedBytes.hashCode ^
      totalPacketsReceived.hashCode ^
      totalPacketsTransmitted.hashCode ^
      totalErrorsOnReceived.hashCode ^
      totalErrorsOnTransmitted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkCumulativeStatsDto &&
          runtimeType == other.runtimeType &&
          totalReceivedBytes == other.totalReceivedBytes &&
          totalTransmittedBytes == other.totalTransmittedBytes &&
          totalPacketsReceived == other.totalPacketsReceived &&
          totalPacketsTransmitted == other.totalPacketsTransmitted &&
          totalErrorsOnReceived == other.totalErrorsOnReceived &&
          totalErrorsOnTransmitted == other.totalErrorsOnTransmitted;
}

/// Network snapshot DTO returned to Dart via FRB.
class NetworkInfoDto {
  const NetworkInfoDto({required this.interfaces});
  final List<NetworkInterfaceDto> interfaces;

  @override
  int get hashCode => interfaces.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkInfoDto &&
          runtimeType == other.runtimeType &&
          interfaces == other.interfaces;
}

/// Static network interface metadata in a snapshot.
class NetworkInterfaceDto {
  const NetworkInterfaceDto({
    required this.name,
    required this.macAddress,
    required this.ipNetworks,
    required this.mtu,
    required this.operationalState,
    required this.cumulative,
  });
  final String name;
  final String macAddress;
  final List<IpNetworkEntryDto> ipNetworks;
  final BigInt mtu;
  final NetworkOperationalStateDto operationalState;
  final NetworkCumulativeStatsDto cumulative;

  @override
  int get hashCode =>
      name.hashCode ^
      macAddress.hashCode ^
      ipNetworks.hashCode ^
      mtu.hashCode ^
      operationalState.hashCode ^
      cumulative.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkInterfaceDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          macAddress == other.macAddress &&
          ipNetworks == other.ipNetworks &&
          mtu == other.mtu &&
          operationalState == other.operationalState &&
          cumulative == other.cumulative;
}

/// Operational state of a network interface.
enum NetworkOperationalStateDto {
  up,
  down,
  testing,
  unknown,
  dormant,
  notPresent,
  lowerLayerDown,
}

/// Per-interface throughput deltas since the last native refresh.
class NetworkThroughputInterfaceDto {
  const NetworkThroughputInterfaceDto({
    required this.name,
    required this.receivedBytes,
    required this.transmittedBytes,
    required this.packetsReceived,
    required this.packetsTransmitted,
    required this.errorsOnReceived,
    required this.errorsOnTransmitted,
  });
  final String name;
  final BigInt receivedBytes;
  final BigInt transmittedBytes;
  final BigInt packetsReceived;
  final BigInt packetsTransmitted;
  final BigInt errorsOnReceived;
  final BigInt errorsOnTransmitted;

  @override
  int get hashCode =>
      name.hashCode ^
      receivedBytes.hashCode ^
      transmittedBytes.hashCode ^
      packetsReceived.hashCode ^
      packetsTransmitted.hashCode ^
      errorsOnReceived.hashCode ^
      errorsOnTransmitted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkThroughputInterfaceDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          receivedBytes == other.receivedBytes &&
          transmittedBytes == other.transmittedBytes &&
          packetsReceived == other.packetsReceived &&
          packetsTransmitted == other.packetsTransmitted &&
          errorsOnReceived == other.errorsOnReceived &&
          errorsOnTransmitted == other.errorsOnTransmitted;
}

/// One network throughput stream tick (plain fields — TDD §4.5).
class NetworkThroughputSampleDto {
  const NetworkThroughputSampleDto({required this.interfaces});
  final List<NetworkThroughputInterfaceDto> interfaces;

  @override
  int get hashCode => interfaces.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkThroughputSampleDto &&
          runtimeType == other.runtimeType &&
          interfaces == other.interfaces;
}
