// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:dart_sysinfo/src/bridge/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_load_average`

/// Returns a TTL-backed OS snapshot (refresh under write lock, TDD §2.2).
OsInfoDto osSnapshot() => RustLib.instance.api.crateApiOsOsSnapshot();

/// One-minute, five-minute, and fifteen-minute load averages.
class LoadAverageDto {
  const LoadAverageDto({
    required this.one,
    required this.five,
    required this.fifteen,
  });
  final double one;
  final double five;
  final double fifteen;

  @override
  int get hashCode => one.hashCode ^ five.hashCode ^ fifteen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoadAverageDto &&
          runtimeType == other.runtimeType &&
          one == other.one &&
          five == other.five &&
          fifteen == other.fifteen;
}

/// Carries §4.3 tri-state load-average semantics for Dart Reading mapping.
class LoadAverageReadingDto {
  const LoadAverageReadingDto({required this.supported, this.value});

  /// False on Windows → Dart `ReadingUnsupported`.
  final bool supported;

  /// None on non-Windows when load average is unavailable → Dart `ReadingUnavailable`.
  final LoadAverageDto? value;

  @override
  int get hashCode => supported.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoadAverageReadingDto &&
          runtimeType == other.runtimeType &&
          supported == other.supported &&
          value == other.value;
}

/// OS snapshot DTO returned to Dart via FRB.
class OsInfoDto {
  const OsInfoDto({
    required this.distributionId,
    required this.distributionIdLike,
    required this.kernelLongVersion,
    required this.uptimeSeconds,
    required this.bootTimeSeconds,
    required this.loadAverage,
    this.name,
    this.kernelVersion,
    this.osVersion,
    this.longOsVersion,
    this.hostName,
  });
  final String? name;
  final String? kernelVersion;
  final String? osVersion;
  final String? longOsVersion;
  final String? hostName;
  final String distributionId;
  final List<String> distributionIdLike;
  final String kernelLongVersion;
  final BigInt uptimeSeconds;
  final BigInt bootTimeSeconds;
  final LoadAverageReadingDto loadAverage;

  @override
  int get hashCode =>
      name.hashCode ^
      kernelVersion.hashCode ^
      osVersion.hashCode ^
      longOsVersion.hashCode ^
      hostName.hashCode ^
      distributionId.hashCode ^
      distributionIdLike.hashCode ^
      kernelLongVersion.hashCode ^
      uptimeSeconds.hashCode ^
      bootTimeSeconds.hashCode ^
      loadAverage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OsInfoDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          kernelVersion == other.kernelVersion &&
          osVersion == other.osVersion &&
          longOsVersion == other.longOsVersion &&
          hostName == other.hostName &&
          distributionId == other.distributionId &&
          distributionIdLike == other.distributionIdLike &&
          kernelLongVersion == other.kernelLongVersion &&
          uptimeSeconds == other.uptimeSeconds &&
          bootTimeSeconds == other.bootTimeSeconds &&
          loadAverage == other.loadAverage;
}
