// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// FRB codegen emits lint suppressions for generated bridge glue.
// ignore_for_file: invalid_use_of_internal_member, unused_import,
//     unnecessary_import

import 'package:dart_sysinfo/src/bridge/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Compile-only FRB surface for M0-03; called from Dart in M0-04.
int frbPlatformSmokePing() =>
    RustLib.instance.api.crateApiSmokeFrbPlatformSmokePing();
